records:
  '2026-02-25':
    B1:
    - 皇台酒业（B1➕砖型图➕回踩白线已确认；前边有根放量阴线）
    - 亚厦股份（B1➕倍量柱➕砖型图2倍➕回踩白线已确认➕一致➕前面跳空➕顶部平量；前边有根假阴真阳的平量）
    - 一心堂（B1➕倍量柱➕关键K➕砖型图反包➕回踩黄线已确认➕一致；前边有根平量长阴还有点无序）
    - 润都股份（B1➕倍量柱➕缩半量➕回踩白线已确认➕一致➕J快速下杀；周线日线都在趋势中）
    - 珀莱雅（B1➕倍量柱➕关键K➕一致；缩量且建仓波且收盘到关键K低最低价之上）
    B2:
    - 招商积余（B2➕倍量柱➕砖型图➕带量穿2线；有点无序）
    - 东方雨虹（B2➕倍量柱➕砖型图➕似突非突）
    - 键邦股份（B2➕倍量柱➕砖型图➕似突非突；周线多头趋势）
    - 凌钢股份（B2➕倍量柱➕砖型图➕似突非突；前面有个缩量的长阴短柱）
    - 滨江集团（B2➕倍量柱➕砖型图➕似突非突；周线多头趋势）
    B3: []
    brick:
    - 亚厦股份
    - 东方雨虹
    - 键邦股份
    - 凌钢股份
    - 滨江集团
    pin: []
  '2026-02-26':
    B1: []
    B2:
    - 宇邦新材
    B3: []
    brick:
    - 创力集团
    - 中来股份
    pin: []
  '2026-02-27':
    B1:
    - 如意集团（1次倍量柱➕回踩白线确认➕一致➕顶部无量➕两天回踩关键K6.6；类似亨通光电万朗磁塑；止损价6.5），
    - 卧龙新能（1次倍量柱➕缩量➕顶部无量➕回踩黄线确认➕倍量柱最低点8.2确认；止损价8.1），
    - 三棵树（1次倍量柱➕缩半量➕顶部无量➕碗里，是不是等回踩下黄线？买入价52.2；止损价买入当根K线最低点*0.97），
    - 福斯特（多次倍量柱➕缩半量➕回踩倍量柱最低价➕倍量柱最低点17.64确认止；止损价17.63），
    - 拓日新能（缩半量➕回踩白线确认；止损价白线下），岱美股份（多次倍量柱➕回踩白线缩量一致；止损白线下）
    - 岱美股份（多次倍量柱➕回踩白线缩量一致，止损白线下）
    B2: []
    B3:
    - 振江股份（多次倍量柱，倍量之后再倍量，止损32）
    brick:
    - 润都股份（多次倍量柱），止损白线下
    pin:
    - 渤海租赁（RSI也满足），只拿一天
