strategy:
  active_period: -2.3
  name: 股票持仓管理配置
  update_time: 2026-02-03
  note:
  - 完美图形干错也要干，出现S1走错也要走
  - 想的是赚钱，而不是暴富，那就会越来越无敌，也就是赚钱就走！
  - 开仓要谨慎，平仓要果断，盈利时要贪心，亏损时要狠心。
  - 正确的交易，即使暂时浮亏，也会因趋势的延续而扭亏为盈；错误的交易，即使暂时浮盈，也会因趋势的反转而回吐利润。
  - 盈利的关键不是抓住所有行情，而是在抓住的行情里赚足利润。
  - 交易的技巧在于，在趋势启动时入场，在趋势反转前离场。
  - 投资者不应该主观地猜测市场的顶和底，应该让市场来告诉我们
  - 在期货交易中，如果投机者入市三天后还没有出现利润，立刻平仓出场
  - 在交易中，投机者应该做出正确的决策，而不是做出让自己感觉舒服的决策，心理上很舒服的交易，结果往往不好
  - 成功的投资者在交易中都能严格限制损失，及时砍掉亏损部位；相反，对盈利头寸尽可能扩大战果
  - 顺势、轻仓、止损、长线；顺势、重仓、相对短的止损、中短线
  - 投资成功的核心不是去抓更多的机会，而是耐心等待，把某一个机会用好，把一个品种做到机会，当机会来临的时候，用极大的意志力把交易机会用到极致
  - 提高业绩的路径不在于发现机会的次数多少，而是在个别好的机会上争取获得大利润
  - 一颗大树想要达到天堂就必须进入最深的土壤，它的根必须进入地狱
  - 交易员在市场中买进卖出的行为背后必然是有一种精神力量的
  - 所谓平衡态下的随机运动就是市场中的震荡，所谓平衡态被打破时的规律运动就是趋势
  - 视角程度的有效性取决于视角转换的彻底性
  - 投资市场不存在放之四海皆准的真理，学会放弃是需要勇气和胆略的，而且是痛苦的
  - 成功的交易者不是赚最多钱的人，而是知道何时停止的人。
  - 不要试图预测市场，要学会应对市场并按规则执行。
  - 不要和市场争论，市场永远是对的。
  - 投资很简单，但并不容易 —— 难在克服贪婪恐惧、坚守原则。
  - 当凡事顺心如意、交易得心应手时，交易者容易被胜利冲昏头脑，从而产生骄傲自满的情绪。
  - 永远不要在亏损的仓位上加仓。
  - 永远别在跌势中加仓，除非你能证明市场错了。
  - 如果市场没有按预期运行，立即离场，不要等亏损扩大。
  - 止损线是生命线，跌破 7% 立即斩首 —— 犹豫即自杀。
  - 如果第一笔交易亏损，绝不做第二笔。
  - 如果你不能接受亏损并按规则离场，就永远无法成功。
  - 纪律是交易的生命线，没有纪律就没有稳定盈利。
  - 没有完美的交易系统，只有完美的执行。
  - 痛苦 + 反思 = 进步。
  - 最危险的时刻通常就是人们开始认为‘这次不一样’的时刻。
  - 恐惧和贪婪是交易者最大的敌人。
  - 人在不确定面前，总是倾向于寻找简单的因果关系。
  - 信心是脆弱的，建立需要很久，摧毁只需一瞬。
  - 机会成本是投资的核心。
  - 在心理上预测行情就行了，但不要轻举妄动，要等待市场证实你的判断。
  - 市场的本身在于不确定性，成功的交易者接受这一点。
  - 每当我失去耐心，未等关键点出现就为蝇头小利入场时，最终总会亏钱。
  - 判断对错并不重要，重要的是正确时获取多大利润，错误时亏损多少。
  - 价格总是沿着阻力最小的方向运动
  - 当方向错误时，你最好做好清仓计划，即使市场在你清仓之后有可能回升，也要坚持这样做。
  - 财富会待在令人意想不到的那一边，更确切地说，失败是在大多数人或者我们脑子里常识性的那一边。
  - 交易是失败者的游戏，你必须学会如何去输。那些每次只输很少一点钱的大输家，却最终都能在交易中生存下去。
  - 一个经过训练的交易员应该知道，成功的法则是：“善输，小错。” 交易成功总是偏心于那些输得少的人、善于输的人。
  - 巨量即是套现良机，什么时候落袋为安？放巨量后三天内全部清仓。
  - 你的思维方式应该是这样：当你的交易正确时，你可以什么也不做；而不是当你的交易不正确时，却袖手旁观！
  - 不要等出现损失后才清除不正确的仓位，永远不要等着市场提醒你已经出错。在市场没有证明你是正确之前，必须假定我们是错的
  - 学会加码！获暴利的捷径只此一途。你必须按照规则二操作：毫无例外并且正确地对你的盈利仓位加码。
  - 我的观点是，不要持有仓位，除非你的交易已经被证明是正确的。
  - 规则一强调的是：你要使你的损失越小越好，割肉越快越好。这样做不会总是正确的，但可以保证你能够在这个游戏中生存。
  - 你的思维方式应该是这样：当你的交易正确时，你可以什么也不做；而不是当你的交易不正确时，却袖手旁观！
hold_stocks:
- stock_code: 000256
  stock_name: 许继电气
  type: B1假阴真阳反包
  stop_loss_price: 28.89
  take_profit_price: 30
  hold_days: 54
  position_ratio: 10.6%
  buy_date:
  - 2025-11-18
  - 2025-11-19
  - 2025-11-21
  - 2026-01-16
  - 2026-01-27
  note: 止损白线牵牛绳
watch_stocks:
- stock_code: 601888
  stock_name: 中国中免
  type: 关注
  stop_loss_price: 0
  hold_days: 0
  note: 海南板块，关注年前消费
- stock_code: 600570
  stock_name: 恒生电子
  type: 关注
  stop_loss_price: 0
  hold_days: 0
  note: 非银龙头
- stock_code: 601066
  stock_name: 中信建投
  type: 关注
  stop_loss_price: 0
  hold_days: 0
  note: 有异动，有合并传闻，但是证券已经变成压盘工具了，现在死叉了
- stock_code: 002279
  stock_name: 久其软件
  type: 关注
  stop_loss_price: 0
  hold_days: 0
  note: AIGC，先启动的
- stock_code: 002594
  stock_name: 比亚迪
  type: 关注
  stop_loss_price: 0
  hold_days: 0
  note: 新能源车/电池龙头，上一波大钱买入的价格在95左右，再等倍量柱
- stock_code: 600519
  stock_name: 贵州茅台
  type: 关注
  stop_loss_price: 0
  hold_days: 0
  note: 大哥回来了
